#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /etc/config/earfcn_lock/network_monitor.sh start
    procd_set_param respawn
    procd_set_param respawn_threshold 10
    procd_set_param respawn_timeout 5
    procd_set_param respawn_retry 5
    procd_close_instance
}

stop_service() {
    # 停止守护进程
    /bin/sh /etc/config/earfcn_lock/network_monitor.sh stop
}

reload_service() {
    stop
    start
}